"""Initial schema

Revision ID: b87af654bdca
Revises: 
Create Date: 2026-04-24 09:55:41.469662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87af654bdca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('password_salt', sa.Text(), nullable=False),
    sa.Column('hash_algorithm', sa.String(), server_default='pbkdf2_sha256', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('encrypted_body', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('code_salt', sa.Text(), nullable=False),
    sa.Column('pbkdf2_iterations', sa.Integer(), server_default='600000', nullable=False),
    sa.Column('cipher_algo', sa.String(), server_default='AES-256-CTR', nullable=False),
    sa.Column('iv_nonce', sa.Text(), nullable=False),
    sa.Column('hmac', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)

    op.create_table('user_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('encrypted_private_key', sa.Text(), nullable=True),
    sa.Column('private_key_iv', sa.Text(), nullable=True),
    sa.Column('private_key_salt', sa.Text(), nullable=True),
    sa.Column('key_cipher_algo', sa.String(), server_default='AES-256-CBC', nullable=False),
    sa.Column('rsa_key_size', sa.Integer(), server_default='2048', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_keys_user_id'), ['user_id'], unique=False)

    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.Text(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_received', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('confirmed_read', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('receipt_text', sa.Text(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('signature_algorithm', sa.String(), server_default='SHA256withRSA', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipts_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipts_message_id'))

    op.drop_table('receipts')
    with op.batch_alter_table('user_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_keys_user_id'))

    op.drop_table('user_keys')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_code'))

    op.drop_table('messages')
    op.drop_table('users')
    # ### end Alembic commands ###
